//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoders.Extrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VEICULOS
    {
        public int ID_VEICULO { get; set; }
        public string NM_LOTE { get; set; }
        public string DS_VEICULO { get; set; }
        public string VL_LANCE_INICIAL { get; set; }
        public int NR_LANCES { get; set; }
        public string VL_AVALIACAO { get; set; }
        public int NR_VISITAS { get; set; }
        public string NR_INSCRICAO_MINIMO { get; set; }
        public string NM_LOCAL { get; set; }
        public string DS_STATUS_VEICULO { get; set; }
    }
}
